<?php
	function menu(){
		echo '<ul class ="nav">
			<li><a href="index.html">Generos</a>
				<ul>
					<li><a href="rock/rock.php">Rock</a></li>
					<li><a href="#">Pop</a></li>
					<li><a href="#">Clasica</a></li>
					<li><a href="#">Reggae</a></li>
					<li><a href="#">Rap</a></li>
				</ul>
			</li>
			<li><a href="#">Más Vendido</a></li>
			<li><a href="#">Más comentados</a></li>
		</ul>';
	}
?>