<?php
	function publicidad(){
		echo '<nav>
			<ul>
				<li><a href="http://jenesaispop.com/">Jenesaispop</a></li>	
				<li><a href="http://www.hipersonica.com/">hipersonica</a></li>
				<li><a href="http://indiespot.es/">indiespot</a></li>
				<li><a href="http://www.mondosonoro.com/">mondosonoro</a></li>
				<li><a href="http://www.indiehoy.com/">indiehoy</a></li>
				<li><a href="http://www.indierocks.mx/">indierocks</a></li>	
				<li><a href="http://www.binaural.es/">binaural</a></li>
				<li><a href="http://www.dodmagazine.es/">dodmagazine</a></li>
				<li><a href="http://muzikalia.com/">muzikalia</a></li>
				<li><a href="http://gladyspalmera.com/">gladyspalmera</a></li>
			</ul>
		</nav>';
	}
?>