<?php
	function genero_disco(){
		echo '<article class = "caratula">
			<img class = "mediana" src="rock/Khri_Khri_20130101/Khri_Khri_20130101.jpg" alt="">
		</article>
		<article class ="comentarios">
			<ol>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
				<li>Comentario.</li>
			</ol>
		</article>
		<article class ="play">
			<a href="rock/Khri_Khri_20130101/khri.html">
			<img class = "pequeña" src="img/ir_play.png" alt="">
			</a>
		</article>';
	}
?>