<?php
	function aniadir_pie(){
		echo '<article>
			<section>
				<address> 
					<p> Universidad de Granada </p> 
					<br />Cuesta del Hospicio, s/n 
					<br />Granada, 18071
				</address>	
			</section>
			<section>
				<img class = "pequeña" src="img/ugr.png" /> 				
			</section>
		</article>
		<article>
			<p>Contacto: <a href="mailo:info@ugr.es">UGR</a></p>
			<p>Contacto: <a href="aralaminos@correo.ugr.es">AUTOR</a></p>
			<p><a href="como_se_hizo.pdf"><img class = "boton_descargar" src="img/pdf.gif" alt=""></a></p>
		</article>';
	 } 
 ?>