CREATE or REPLACE PROCEDURE registrar_incidencia (DNI_U in INTEGER,	descripcion in VARCHAR2, ID_ZONA in INTEGER, cantidad in BINARY_DOUBLE) AS
	
  CURSOR vecinos IS SELECT DNI FROM propietario;
  
  CNT INTEGER;
  fecha DATE;
  NUM_INCIDENCIA INTEGER;
  NUM_RECIBO INTEGER;
  NUM_EMPRESA INTEGER;
  CANTIDAD_FINAL BINARY_DOUBLE;
  

BEGIN

  INSERT INTO REGISTRAR(DNI) VALUES (DNI_U);
  
  SELECT ID_INCIDENCIA INTO NUM_INCIDENCIA FROM REGISTRAR WHERE DNI=DNI_U;
  INSERT INTO GENERARECIBOINCIDENCIA(ID_INCIDENCIA) VALUES (NUM_INCIDENCIA);
  
  SELECT ID_RECIBO INTO NUM_RECIBO FROM GENERARECIBOINCIDENCIA WHERE ID_INCIDENCIA=NUM_INCIDENCIA;
  INSERT INTO RECIBO VALUES (NUM_RECIBO, sysdate(), cantidad);  
  
  SELECT ID_EMPRESA INTO NUM_EMPRESA FROM EMPRESA;
  SELECT FECHA INTO fecha FROM RECIBO WHERE ID_RECIBO=NUM_RECIBO;
  INSERT INTO INCIDENCIAS (ID_ZONA, ID_EMPRESA, descripcion, fecha_incidencia) VALUES (ID_ZONA, NUM_EMPRESA, descripcion, fecha);
  
  OPEN vecinos;
  
    LOOP
      FETCH vecinos INTO CNT;
      EXIT WHEN vecinos%NOTFOUND;
      
      cantidad_FINAL := cantidad/CNT;      
    END LOOP;
    
    LOOP
      FETCH vecinos INTO CNT;
        INSERT INTO RECIBO_MANTENIMIENTO (ID_RECIBO, DNI, ID_ZONA, descripcion, FECHA_REPARACION, CANTIDAD_DINERO) VALUES (NUM_RECIBO, DNI_U, ID_ZONA, descripcion, fecha, cantidad);
      EXIT WHEN vecinos%NOTFOUND;
          
    END LOOP;
    
  CLOSE vecinos;
     

END registrar_incidencia;